### ISSUE TITLE
About the attention type in the example config file

### ISSUE THREAD

**Issue by Balladen** [s-omranpour/MIDI-Transformer#1]
```
if x_mask is None:
            if self.self_attention_type.startswith('causal'):
                x_mask = TriangularCausalMask(x.size(1), device=x.device)
            else:
                x_mask = FullMask(x.size(1), device=x.device)
```
I thought TriangularCausalMask should be used when training a music generation model, but the self attention type in the example config is "linear". Should I add 'causal' before it?

**Comment by s-omranpour** [comment]
Hey,

That's right. When training with causal language modeling objective, the self-attention type should be causal. I will correct it in the config file. 

best
